name: dartsult
description: A library implements Rust style [Result] for Dart error handle.
version: 0.1.3
homepage: https://github.com/al8n/dartsult
repository: https://github.com/al8n/dartsult



environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.0